name: Test Workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Set up Python
        run: uv python install

      - name: Set up pyyaml
        run: uv sync

      - name: Run Justfile tasks
        run: just test
