name: Test Workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the changed files back to the repository.
      contents: write

    if: "contains(github.event.head_commit.message, 'binenv-tests')"

    steps:
      - name: Add binenv to path
        shell: bash
        run: echo "/home/runner/.binenv" >> $GITHUB_PATH

      - name: Check out code
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Install binenv
        run: wget 'https://raw.githubusercontent.com/axgkl/binaries/refs/heads/master/binenv-install.sh' -O - | bash

      - name: Set up Python
        run: uv python install

      - name: Set up pyyaml
        run: uv sync

      - name: Run Justfile tasks
        run: just test

      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: binenv-tests
