name: Test Workflow
on:
  push:
    branches:
      - master
jobs:
  test:
    runs-on: ubuntu-latest

    if: "contains(github.event.head_commit.message, 'binenv-tests')"

    steps:
      - name: Add binenv to path
        shell: bash
        run: echo "/home/runner/.binenv" >> $GITHUB_PATH

      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Just
        uses: extractions/setup-just@v2

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          version: "0.6.1"

      - name: Install binenv
        run: wget 'https://raw.githubusercontent.com/axgkl/binaries/refs/heads/master/binenv-install.sh' -O - | bash

      - name: Set up Python
        run: uv python install

      - name: Set up pyyaml
        run: uv sync

      - name: Run Justfile tasks
        run: just test

      - name: Check for Changes
        id: check_changes
        run: |
          if [[ -n "$(git diff --exit-code)" ]]; then
            echo "Changes detected."
            echo "::set-output name=has_changes::true"
          else
            echo "No changes detected."
            echo "::set-output name=has_changes::false"
          fi

      - name: Commit and Push Changes
        if: steps.check_changes.outputs.has_changes == 'true'
        run: |
          # configure user
          git config --global user.name "${{ github.actor }}"
          git config --global user.email "${{ github.actor }}@users.noreply.github.com"
          git add .
          git commit -m 'files changed'
          git push
